// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

function getSupabaseEnvironment() {
  return {
    SUPABASE_URL:
      import.meta.env.VITE_SUPABASE_URL ||
      import.meta.env.SUPABASE_URL ||
      (typeof process !== "undefined"
        ? process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL
        : undefined),
    SUPABASE_ANON_KEY:
      import.meta.env.VITE_SUPABASE_ANON_KEY ||
      import.meta.env.SUPABASE_ANON_KEY ||
      (typeof process !== "undefined"
        ? process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY
        : undefined),
  };
}

function createSupabaseClient() {
  const { SUPABASE_URL, SUPABASE_ANON_KEY } = getSupabaseEnvironment();

  const missing = [
    ...(!SUPABASE_URL ? ["VITE_SUPABASE_URL"] : []),
    ...(!SUPABASE_ANON_KEY ? ["VITE_SUPABASE_ANON_KEY"] : []),
  ];

  if (missing.length > 0) {
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Add ${missing.join(" and ")} to .env or .env.local and restart Vite.`;
    console.error("[Supabase]", message, {
      "import.meta.env.VITE_SUPABASE_URL": import.meta.env.VITE_SUPABASE_URL,
      "import.meta.env.VITE_SUPABASE_ANON_KEY": import.meta.env.VITE_SUPABASE_ANON_KEY,
    });
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // Autoriser Supabase à détecter la session dans l'URL (utile pour OAuth redirects
      // et pour s'assurer que la session initiale est correctement restaurée en WebView).
      detectSessionInUrl: true,
      // Supabase s'attend à recevoir une fonction de lock. Fournir une no-op
      // async function évite l'erreur "this.lock is not a function" tout en
      // désactivant le verrouillage effectif.
      lock: async (name: string, acquireTimeout: number, fn: () => Promise<any>) => {
        return await fn();
      },
    },
  });
}

// Ensure a single Supabase client instance across module reloads / multiple bundles.
type GlobalForSupabase = {
  supabase?: ReturnType<typeof createSupabaseClient>;
};

const globalForSupabase = (globalThis as unknown) as GlobalForSupabase & typeof globalThis;

const _supabase = globalForSupabase.supabase || createSupabaseClient();

// Expose the instance globally in non-production to survive HMR / StrictMode double-mounts
if (process.env.NODE_ENV !== "production") {
  globalForSupabase.supabase = _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = _supabase;
